name: 纯净兼容打包
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: JDK17稳定环境
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: 生成匹配Gradle
      run: gradle wrapper --gradle-version 7.5

    - name: 修复权限
      run: find . -name gradlew -exec chmod +x {} \;

    - name: 忽略仓库规则 强制编译
      run: |
        echo 'systemProp.gradle.repository.prefer.settings=false' >> gradle.properties
        ./gradlew clean assembleRelease --warning-mode none --continue

    - name: 保存成品APK
      uses: actions/upload-artifact@v4
      with:
        name: 最终可用APK
        path: "**/release/*.apk"
